### ISSUE TITLE
Change `ostypeid` from int to string/uuid

### ISSUE THREAD

**Issue by marcaurele** [exoscale/egoscale#107]
Can you prepare the change to move from int to uuid for the ostypeid in the response of `listVirtualMachines`. This has been reported upstream too and a change is awaiting validation/discussion: https://github.com/apache/cloudstack/pull/2608

**Comment by greut** [comment]
That will do it.

```
$ cs listApis > listApis.json
$ go run generate/main.go -apis listApis.json -cmd listVirtualMachine
```
