### ISSUE TITLE
improve error message for Get using Payload

### ISSUE THREAD

**Issue by greut** [exoscale/egoscale#153]
context https://github.com/exoscale/exoip/blob/4b6c67e461495317288803a0c8eeb263e794cbd3/engine.go#L196-L207

the `.Get` can be a complex call, and the error message saying `id: %s, name: %s` is not good enough in some cases.

https://github.com/exoscale/egoscale/blob/master/virtual_machines.go#L36

**Idea** we could use the [`Payload`](https://godoc.org/github.com/exoscale/egoscale#Client.Payload) of the request to show the *actual* request made.

**Comment by pierre-emmanuelJ** [comment]
in List() payload return e.g `apikey=EXOxxxxxxxxxxxxxxxxxxxxxxx&command=listVirtualMachines&response=json`

**Comment by pierre-emmanuelJ** [comment]
i can complete `List()` error with payload informations

**Comment by pierre-emmanuelJ** [comment]
@greut

**Comment by greut** [comment]
that's perfect!
