### ISSUE TITLE
RFC: split compute and dns

### ISSUE THREAD

**Issue by greut** [exoscale/egoscale#164]
With the upcoming `vgo` changes and the ever growing list of files you have to go through before reaching the README, it will be probably be the time to move packages files around.

- `github.com/exoscale/egoscale/cmd/cs`
- `github.com/exoscale/egoscale/cmd/exo`
- **new** `github.com/exoscale/egoscale/compute` to contains all the cloudstack related files
- **new** `github.com/exoscale/egoscale/dns` to contains all the dns related files
- `github.com/exoscale/egoscale` will be empty

**Comment by pierre-emmanuelJ** [comment]
👍
