### ISSUE TITLE
exo firewall add X http https only creates http

### ISSUE THREAD

**Issue by greut** [exoscale/egoscale#186]
```
$ exo firewall add rancher http https
```

|  TYPE   |     SOURCE     | PROTOCOL |   PORT    | DESCRIPTION |                  ID                  |
|---------|----------------|----------|-----------|-------------|--------------------------------------|
| INGRESS | CIDR 0.0.0.0/0 | tcp      | 80 (http) |             | 7372b893-42ca-465e-8596-ff8de5dad088 |

is it easy to support multiple rules ?

**Comment by pierre-emmanuelJ** [comment]
good idea 👍
