### ISSUE TITLE
exo template list <??>

### ISSUE THREAD

**Issue by greut** [exoscale/egoscale#205]
two little things with `template list`

`template := &egoscale.Template{IsFeatured: true, ZoneID: "1"}`

1. it promotes bad usage of the API with the `ZoneID = 1`, when it should use the `defaultZone` instead
2. it could take another set of arguments given to `keyword`

```
$ exo template list LTS
"Linux Ubuntu 18.04 LTS 64-bit 10G Disk (2018-04-26-0e6133)"
"Linux Ubuntu 16.04 LTS 64-bit 10G Disk (2018-03-02-5858e9)"
````

**Comment by pierre-emmanuelJ** [comment]
it's `exo template`and not `exo template list`

👍 yes `zoneID` now have to be `defaultZone`

for `keyword` why not but changing `exo template` by `exo template list` could be better

**Comment by greut** [comment]
I was using `exo template list` all along, so go ahead.
