### ISSUE TITLE
Incorrect API result on listAccounts

### ISSUE THREAD

**Issue by marcaurele** [exoscale/egoscale#256]
When running commands, I get a different result if I use egoscale vs our python `cs` lib for `cs listAccounts id=xxx --region=yyy` (`yyy` being an admin account)

- Egoscale returns the current account linked to the region (not taking into consideration the `id` parameter?)
- CS python returns the account linked to the `id` parameter, which is my expectation

**Comment by greut** [comment]
`--id=xxx` and not `id=...`. In doubt, use `-D` to show the URL.

**Comment by marcaurele** [comment]
IMO if the command isn't compatible `as-is` with the python cs lib, we should name the executable differently. What do you think?

**Comment by greut** [comment]
the ultimate goal is to move everything into exo
