### ISSUE TITLE
exo: json output

### ISSUE THREAD

**Issue by mcorbin** [exoscale/egoscale#280]
Is it possible to add a --raw (or --json) flag to exo commands to have the json returned by the API ? It will be easier for sysadmin to write scripts using exo.

For example:

```console
% exo privnet list --json |  jq '{count: .count}'
```

```
{
  "count": 7
}
```

**Comment by pierre-emmanuelJ** [comment]
`exo` return not the same informations like api it's an hight level user interface.

## e.g
```
$ exo template ls
```
|       OPERATING SYSTEM        | DISK |   RELEASE DATE    |                  ID                  |
|-------------------------------|------|-------------------|--------------------------------------|
| Linux CentOS 7.5 64-bit       |      |                   | 909ce5b7-2132-4ff0-9bf8-aadbb423f7d9 |
| Linux CentOS 7.4 64-bit       |      | 2018-01-08-d617dd | 1b0b9253-929e-4865-874b-7d2c3491987b |
| Linux CentOS 6.9 64-bit       |      | 2018-01-08-8856b8 | cfb832b9-edce-46fa-abb4-a45454ca97ac |
| Linux Centos 7 Atomic         |      |                   | c5a139df-74ac-4279-b467-6a9a11fd6fc8 |
......

this output is like on the website list (sorted, formated...)

## This `exo` command is like this on `cs`:

```
$ cs listTemplates --templatefilter featured --zoneid 1128bd56-b4d9-4ac6-a7b9-c715b187ce11

{
  "count": 54,
  "template": [
    {
      "account": "admin",
      "checksum": "eaf71bb8f067ed6f5c9fbfe9b9b6ed9e",
      "created": "2018-06-21T12:39:16+0200",
      "crossZones": true,
      "details": {
        "username": "centos"
      },
      "displaytext": "Linux CentOS 7.5 64-bit 10G Disk",
      "domain": "ROOT",
      "domainid": "4a8857b8-7235-4e31-a7ef-b8b44d180850",
      "format": "QCOW2",
      "hypervisor": "KVM",
      "id": "909ce5b7-2132-4ff0-9bf8-aadbb423f7d9",
      "isextractable": true,
      "isfeatured": true,
      "ispublic": true,
      "isready": true,
      "name": "Linux CentOS 7.5 64-bit",
      "ostypeid": "0e49fe1a-0265-4158-b862-0f90d1d100a1",
      "ostypename": "Linux CentOS (64-bit)",
      "passwordenabled": true,
      "size": 10737418240,
      "templatetype": "USER",
      "zoneid": "1128bd56-b4d9-4ac6-a7b9-c715b187ce11",
      "zonename": "ch-gva-2"
    },
......
......
```

so for specific api output you have to use `cs` or in a next version of `exo` the command `exo api` will be integrate and implemented like `cs`

**Comment by mcorbin** [comment]
Yes i can use cs for now, but i think we will also need json output for non related cs calls in the future.

**Comment by greut** [comment]
@mcorbin that's not a good example of a use case, imho. `cs listNetworks` does what you want here.

**Comment by mcorbin** [comment]
For this specific example i can use cs, but i think it could be nice to be able to do it with exo (so i could use exo for everything and not a combination of exo + cs).

**Comment by greut** [comment]
> Yes i can use cs for now, but i think we will also need json output for non related cs calls in the future.

Let's talk about things in the future once we get there.

**Comment by mcorbin** [comment]
> Let's talk about things in the future once we get there.

We could also think about it right now for not having to rewrite everything when we will be there.

**Comment by greut** [comment]
@mcorbin what do you suggest can be done now to help in the future?

**Comment by mcorbin** [comment]
Maybe it will be easier to think about it right now in the code.

**Comment by greut** [comment]
We're going in circles here.

**Comment by brutasse** [comment]
It doesn't seem there's much to do now. `aws-cli` has `aws s3` for the high-level stuff and `aws s3api` for mapping directly to API calls. That's one way to do it that shouldn't alter the way things are designed in the higher-level interface.

**Comment by pierre-emmanuelJ** [comment]
It's not the good philosophy to display high-level output in Json or display api result, it's doesn't match and  it's doesn't make sense. Low level interface is here for api calls.
