### ISSUE TITLE
move to go modules

### ISSUE THREAD

**Issue by greut** [exoscale/egoscale#298]
Potential issues:

- we have multiple `Gopkg.toml`, it will potentially break
- `gometalinter`

Solutions:
- vendor all the things
- split to multiple repositories
- both
- wait (for gometalinter mostly)

(that's what I know from my experiments with https://github.com/exoscale/exoip/pull/51 so far)

**Comment by pierre-emmanuelJ** [comment]
break with go1.11 ?

**Comment by pierre-emmanuelJ** [comment]
https://github.com/exoscale/egoscale/pull/299
