### ISSUE TITLE
why create a new SSH key

### ISSUE THREAD

**Issue by sebgoa** [exoscale/egoscale#311]
I like the simplicity of `exo vm create foobar`

but it creates a new SSH key:

```
$ exo vm create barbaz
Creating private SSH key
Deploying "barbaz" 100 % [======================================] done

What to do now?

1. Connect to the machine

> exo ssh barbaz
ssh -i "/Users/sebastiengoasguen/.exoscale/instances/2c5b53cb-c469-4209-8970-18f6ac913b88/id_rsa" ubuntu@185.19.30.86

2. Put the SSH configuration into ".ssh/config"

> exo ssh barbaz --info
Host barbaz
	HostName 185.19.30.86
	User ubuntu
	IdentityFile /Users/sebastiengoasguen/.exoscale/instances/2c5b53cb-c469-4209-8970-18f6ac913b88/id_rsa

Tip of the day:
	You're the sole owner of the priva
```

Why not use the default SSH key - if there is one-

**Comment by greut** [comment]
> Why not use the default SSH key - if there is one-

Sadly, that information doesn't surface in the API and is a feature from the Exoscale portal itself. That information could be put in the config file (toml), like the default zone but it wouldn't match the online experience. Probably confusing.

Also, the CloudStack layer has trouble recalling with SSH key created which instance as it does the matching using the fingerprint while letting you submit the same key multiple time.

Do you think having something like `defaultKeyPair="my-key"` would work while be decorrelated to the web UI?

Ideally, we could manage the ssh key via the cloud-init and have more than one. Which isn't supported by the API.

**Comment by greut** [comment]
great, thanks for the feedback.
