### ISSUE TITLE
how to set a default cloud-init file

### ISSUE THREAD

**Issue by sebgoa** [exoscale/egoscale#313]
I have written a cloud-init script that I want all my VMs to use (all the time).

How could I make it a default ? Ideally I would be able to manage my cloud-init files from the console and then specify one of them as defaults.

That way `exo vm create foofoo -f foo.sh ` becomes `exo vm create foofoo`

**Comment by pierre-emmanuelJ** [comment]
That's a good idea ! It can be possible to put default cloud init file path into EXO configuration

**Comment by greut** [comment]
What is hard is to draw the line between the quick CLI and a bigger tool like terraform or ansible. We have a hard time fighting the NIH syndrome.
