### ISSUE TITLE
Add basic installation step in the README

### ISSUE THREAD

**Issue by sebgoa** [exoscale/egoscale#315]
The README makes you click to get to the doc to see the install steps.

Why not writing the 5 lines install step directly in the README saving everyone one click :)

**Comment by greut** [comment]
@sebgoa the cli side of this repo will be moved to its own repository to ease the usage of go module (1.11). We will aim to make this step clearer. The last blocker is #182.

**Comment by greut** [comment]
will be done over there: https://github.com/exoscale/cli
