### ISSUE TITLE
config: not written due to endpoint failure

### ISSUE THREAD

**Issue by marcaurele** [exoscale/egoscale#318]
When the remote endpoint is not available, it's impossible to add an entry and it crashed the whole import.

1. write each configuration entry in the file as soon as possible
2. don't exit when the endpoint does not reply

```
[+] Account name [blabla]: 
Get http://localhost:8080/client/api?apikey=blablablablablabl&command=listZones&page=1&pagesize=50&response=json&signature=blablablablabl%3D: dial tcp [::1]:8080: connect: connection refused
<program exits & no config written>
```

**Comment by greut** [comment]
good catch!
