### ISSUE TITLE
On credential storage

### ISSUE THREAD

**Issue by Fnux** [exoscale/egoscale#330]
Hello,

The `exo` command line utility seems very convenient, but the way it stores credentials bothers me: it doesn't make sense to use 2FA to authenticate against [portal.exoscale.com](https://portal.exoscale.com/) while a plaintext file containing API credentials working for *any* services sits on my disk. Is there a way - or is it planned - to sources these credentials from an external command ? I'd like to source the secret from my [pass](https://www.passwordstore.org/)word store.

Thank you!

**Comment by greut** [comment]
@Fnux do you have any tools in mind that does it correctly?

**Comment by Fnux** [comment]
In order to easily interface with any setup, I believe the easiest way would be to read the output of an external command (by adding a `secreteval` field to the `exoscale.toml` configuration file):

```
defaultaccount = "example"

[[accounts]]
  account = "example"
  computeEndpoint = "https://api.exoscale.ch/compute"
  defaultTemplate = ""
  defaultZone = "ch-gva-2"
  dnsEndpoint = "https://api.exoscale.ch/dns"
  key = "example-key"
  name = "inilab"
  # Using https://www.passwordstore.org/
  secreteval =  "pass show exoscale/example-secret | head -n 1"
```

**Comment by greut** [comment]
@Fnux it sounds simple enough, love it. _eval is evil_ :wink:
