### ISSUE TITLE
factor out the auths

### ISSUE THREAD

**Issue by greut** [exoscale/egoscale#371]
A new namespace, .e.g. `github.com/exoscale/egoscale/auth`, with the various strategies.

- `auth.CloudStackV3`
- `auth.ExoscaleHmacSha256`
- `auth.ExoscaleDnsToken`

So we finally decorrelate the API from the Auth.

```go
// cloudstack client
cs := NewClient(endpoint, apiKey, auth.NewCloudStack(apiSecret))
// cloudstack client signatureVersion=3
cs := NewClient(endpoint, apiKey, auth.NewCloudStackV3(apiSecret, expiration))
// runstatus client
cs := NewClient(endpoint, apiKey, auth.NewExoscaleHmacSha256(apiSecret))
// dns client
cs := NewClient(endpoint, apiKey, auth.NewExoscaleDnsToken(apiSecret))
// no auth, for the tests
cs := NewClient(endpoint, apiKey, nil)
```

**Comment by pierre-emmanuelJ** [comment]
Since there are other service like Cloudstack, dns, runstatus I think can be more explicite. Yes indeed

**Comment by falzm** [comment]
The egoscale API is pending major rewrite, authentication management will be revamped.
