### ISSUE TITLE
ErrNotFound error type

### ISSUE THREAD

**Issue by falzm** [exoscale/egoscale#378]
In order to make egoscale more user-friendly, especially in case of returning a CS error upon action on a non-existent resource, I suggest creating a new `ErrNotFound` error type to signal clearly to the user that the resource it wants to manipulate doesn't exist, so he/she can handle this specific error case more gracefully downstream.

```golang
const ErrNotFound = fmt.Errorf("resource not found")
```

For instance, when getting this kind of return from the CS API:

`API error ParamError 431 (CSErrorCode(0) 0): not found, query: apikey=EXOxxxxxxxxxxxxxxx, command=listVirtualMachines, expires=2018-12-07T17%3A32%3A13%2B0100, name=blah, response=json, signatureversion=3`

We could parse the return message and look for the `not found` pattern, and if found return the `ErrNotFound` type instead of the raw error?

**Comment by greut** [comment]
There is nothing to be parsed, it's an [ErrorResponse](https://godoc.org/github.com/exoscale/egoscale#ErrorResponse), however something along the lines of [IsNotExist](https://godoc.org/os#IsNotExist) could probably be useful.

**NB:** `Get`/`List` semantic changes with 0.13 #363.

**Comment by falzm** [comment]
A `IsNotExist()` would be fine too.
