### ISSUE TITLE
v0.12.5 introduced a regression in exoscale/cli

### ISSUE THREAD

**Issue by falzm** [exoscale/egoscale#380]
Change 9c630ab71922488743c23f78fb8182c13d64568d removed the `UserSecurityGroupList` field from struct `IngressRule`, which is still used in cli [cmd/firewall.go](https://github.com/exoscale/cli/blob/master/cmd/firewall.go#L32-L33):

```console
$ go build -mod=vendor -o exo
# github.com/exoscale/cli/cmd
cmd/firewall.go:32:32: rule.UserSecurityGroupList undefined (type *egoscale.IngressRule has no field or method UserSecurityGroupList)
cmd/firewall.go:33:27: rule.UserSecurityGroupList undefined (type *egoscale.IngressRule has no field or method UserSecurityGroupList)
make: *** [exo] Error 2
```

**Comment by greut** [comment]
https://github.com/exoscale/cli/pull/66/commits/0cf7fd329e85b2a30f39c0b390c03b9f4d3d057b
