### ISSUE TITLE
go modules: retract v1.19.0

### ISSUE THREAD

**Issue by ldez** [exoscale/egoscale#482]
When you will update your minimal version to go 1.16

https://github.com/exoscale/egoscale/blob/d88efb2cc1672a19f816eab75c7b94c2234ff96e/go.mod#L13

Could you add the following `retract` directives:

```go
retract (
    v1.19.0 // add explanation
)
```

https://pkg.go.dev/github.com/exoscale/egoscale?tab=versions

- https://blog.golang.org/go116-module-changes#TOC_5.
- https://golang.org/ref/mod#go-mod-file-retract

Thank you.

**Comment by dmke** [comment]
Looks like v1.19.0 has been accidentally published the same day v0.19.0 was:

![image](https://user-images.githubusercontent.com/327411/110868645-3e49e680-82c9-11eb-9c0a-587491389dc8.png)

In Lego, we've fallen twice into the trap of upgrading to "v1.19.0" now :-)

**Comment by szuecs** [comment]
@pierre-emmanuelJ deletion of the git tag v1.19.0 does not help because it's in proxy.golang.org and it's also in https://github.com/kubernetes-sigs/external-dns/blob/v0.11.0/go.mod#L23
