### ISSUE TITLE
Is there a way to access usage records (e.g. for FinOps use cases)

### ISSUE THREAD

**Issue by avaliaexpert** [exoscale/egoscale#583]
Hello,

In the portal, there is a UI to view usage records, in the billing section. I see calls to this API: https://portal.exoscale.com/api/usage.

Is there a way to access this information with an official API (or is that on the roadmap?).

**Comment by brutasse** [comment]
Hi @avaliaexpert

It's indeed on the roadmap - in fact already available and being polished as we speak. Monthly detailed usage reports are available to customers who subscribe to the "Starter" [support plan](https://www.exoscale.com/support/#support-table).

They take the form of JSON files exported to a bucket owned by the customer, with granularity at the billing entity (compute instance, SOS bucket, …)

An API endpoint with aggregated usage (similar to the portal endpoint you cited) will be available for all customers at a later stage.

Feel free to reach out to Support if interested. In the meantime I'm closing this ticket as support for the aggregated usage endpoint will come once the API is ready.

Thanks!

**Comment by avaliaexpert** [comment]
Great, thanks!
