### ISSUE TITLE
some examples for basic usage

### ISSUE THREAD

**Issue by nbari** [exoscale/egoscale#72]
Hi, could you share some basic examples of how to query for example running instances, fetch tags of them etc, something that could replace for example the python `cs`:

    $ cs listVirtualMachines state=Running | jq

**Comment by nbari** [comment]
Came up with, but probably an `examples` dir could help a little more:

```go
package main

import (
	"fmt"
	"log"

	"github.com/exoscale/egoscale"
)

func main() {
	cs := egoscale.NewClient("https://api.exoscale.ch/compute", "key", "secret")

	vms, err := cs.Request(&egoscale.ListVirtualMachines{})
	if err != nil {
		log.Fatal(err)
	}

	count := vms.(*egoscale.ListVirtualMachinesResponse).Count
	fmt.Printf("count: %d\n", count)

	for _, vm := range vms.(*egoscale.ListVirtualMachinesResponse).VirtualMachine {
		fmt.Printf("name: %s, IP: %s\n", vm.DisplayName, vm.Nic[0].IPAddress)
	}
}

```

**Comment by greut** [comment]
@nbari checkout the wip branch, https://github.com/exoscale/egoscale/pull/33

**Comment by greut** [comment]
Btw, if you think of a good example for the README. That would be greatly appreciated.

**Comment by greut** [comment]
@nbari https://github.com/exoscale/egoscale/releases/tag/v0.9.22a0
