### ISSUE TITLE
Test coverage : each functions

### ISSUE THREAD

**Issue by pierre-emmanuelJ** [exoscale/egoscale#81]

**Comment by pierre-emmanuelJ** [comment]
@greut i'll do a pull request ASAP

**Comment by greut** [comment]
what I was thinking about would be a generic way of testing them.

```
commands := []ListCommand{&ListZones{}, &ListNetworks{}, ...}

for _, command := range commands {
    // the same test
}
```

**Comment by greut** [comment]
meaning, adding new commands doesn't cost us too much copy'n'pasting of test code. Because it's boring and cumbersome.

**Comment by pierre-emmanuelJ** [comment]
Good idea i'll do that

**Comment by pierre-emmanuelJ** [comment]
All items have an ID but to make a request sometime some commands have required fields

**Comment by greut** [comment]
we probably are allowed to pre-fill some of them.

```go
commands := []ListCommand{
    &ListZones{},
    &ListNetworks{},
    &ListNics{VirtualMachineID: "1"},
}
```

**Comment by pierre-emmanuelJ** [comment]
It's not very cool because i have to format all responses to match with query
```
{"listvirtualmachinesresponse": {
			"count": 3,
			"virtualmachine": [
				{
					"id": "84752707-a1d6-4e93-8207-bafeda83fe15"
				},
				{
					"id": "f93238e1-cc6e-484b-9650-fe8921631b7b"
				},
				{
					"id": "487eda20-eea1-43f7-9456-e870a359b173"
				}
			]
		}}
```

**Comment by greut** [comment]
it could be for buggy outputs, like errors and empty results which look alike.

**Comment by greut** [comment]
cf #83
