### ISSUE TITLE
Missing commands [RFC]

### ISSUE THREAD

**Issue by greut** [exoscale/egoscale#92]
Please tick the useful commands you'd want to see added.

- [ ] `createVPCOffering`
- [ ] `ldapCreateAccount`
- [ ] `createPod`
- [ ] `removeRawUsageRecords`
- [ ] `copyIso`
- [ ] `deleteAutoScaleVmProfile`
- [ ] `addExternalFirewall`
- [ ] `deleteExternalLoadBalancer`
- [ ] `listVirtualMachinesMetrics`
- [ ] `deleteStoragePool`
- [x] `listHosts`
- [ ] `updateStoragePool`
- [x] `rebootSystemVm`
- [ ] `importLdapUsers`
- [x] `listDedicatedZones`
- [ ] `listElastistorPool`
- [ ] `updateFirewallRule`
- [ ] `quotaIsEnabled`
- [ ] `listSrxFirewalls`
- [x] `listHypervisors`
- [ ] `deleteAccountFromProject`
- [ ] `getSolidFireVolumeAccessGroupId`
- [ ] `updateGuestOs`
- [x] `updateResourceLimit` #128
- [ ] `deleteStaticRoute`
- [ ] `listHostsMetrics`
- [x] `releaseDedicatedPod`
- [ ] `deleteRemoteAccessVpn`
- [ ] `updateNetworkACLList`
- [ ] `deleteNiciraNvpDevice`
- [ ] `deleteEvents`
- [ ] `listUcsBlades`
- [ ] `notifyBaremetalProvisionDone`
- [ ] `getVolumeSnapshotDetails`
- [x] `deleteIso`
- [ ] `deleteExternalFirewall`
- [x] `updateHost`
- [ ] `createEgressFirewallRule`
- [x] `listVPCOfferings`
- [ ] `getSolidFireVolumeSize`
- [ ] `uploadVolume`
- [ ] `configureOutOfBandManagement`
- [ ] `listStorageTags`
- [ ] `listTemplatePermissions`
- [x] `destroySystemVm`
- [ ] `archiveEvents`
- [ ] `addSwift`
- [ ] `deleteSecondaryStagingStore`
- [ ] `addSrxFirewall`
- [ ] `updateLoadBalancer`
- [ ] `scaleSystemVm`
- [x] `listSnapshotPolicies`
- [ ] `updateVpnCustomerGateway`
- [ ] `stopRouter`
- [ ] `lockAccount`
- [x] `listClusters`
- [ ] `deleteProjectInvitation`
- [ ] `listProjectInvitations`
- [ ] `listEgressFirewallRules`
- [ ] `deleteTrafficType`
- [ ] `updateRegion`
- [ ] `listClustersMetrics`
- [ ] `listLdapConfigurations`
- [ ] `listSecondaryStagingStores`
- [ ] `createRemoteAccessVpn`
- [ ] `startRouter`
- [x] `listGuestOsMapping`
- [ ] `deleteStratosphereSsp`
- [ ] `createAutoScalePolicy`
- [ ] `listPhysicalNetworks`
- [ ] `listFirewallRules`
- [ ] `deleteBrocadeVcsDevice`
- [ ] `cleanVMReservations`
- [x] `extractIso`
- [ ] `createSecondaryStagingStore`
- [ ] `removeVmwareDc`
- [ ] `listInternalLoadBalancerElements`
- [ ] `updateLBHealthCheckPolicy`
- [ ] `createLoadBalancerRule`
- [ ] `addGuestOsMapping`
- [ ] `disableOutOfBandManagementForZone`
- [ ] `configureF5LoadBalancer`
- [x] `updateNetworkOffering`
- [ ] `updateVPC`
- [ ] `changeOutOfBandManagementPassword`
- [ ] `deleteEgressFirewallRule`
- [x] `stopSystemVm`
- [x] `listResourceDetails` #99
- [ ] `createNetworkOffering`
- [x] `dedicateCluster`
- [ ] `createIpForwardingRule`
- [ ] `listVolumesMetrics`
- [ ] `listElastistorInterface`
- [ ] `listSslCerts`
- [x] `listPrivateGateways`
- [ ] `updateVmNicIp`
- [ ] `updateLBStickinessPolicy`
- [x] `listPods`
- [ ] `startInternalLoadBalancerVM`
- [ ] `updateDiskOffering`
- [ ] `deleteSrxFirewall`
- [ ] `addAccountToProject`
- [ ] `resetVpnConnection`
- [ ] `createAutoScaleVmGroup`
- [ ] `searchLdap`
- [ ] `deleteLoadBalancerRule`
- [ ] `addBaremetalPxePingServer`
- [ ] `listPortableIpRanges`
- [x] `getVirtualMachineUserData` #103 
- [x] `listConfigurations`
- [ ] `disableStaticNat`
- [ ] `deleteUcsManager`
- [x] `deleteHost`
- [x] `listCapabilities`
- [ ] `releaseDedicatedZone`
- [ ] `updateTrafficType`
- [ ] `listConditions`
- [ ] `updateNetworkServiceProvider`
- [ ] `removeFromLoadBalancerRule`
- [ ] `addNuageVspDevice`
- [ ] `createStaticRoute`
- [ ] `addTrafficType`
- [ ] `deletePrivateGateway`
- [ ] `listLoadBalancerRuleInstances`
- [ ] `deleteCondition`
- [ ] `updateDomain`
- [ ] `updatePhysicalNetwork`
- [ ] `disableAutoScaleVmGroup`
- [ ] `createSnapshotPolicy`
- [ ] `deleteNuageVspDevice`
- [ ] `createRolePermission`
- [x] `listSystemVms`
- [ ] `createProject`
- [ ] `assignCertToLoadBalancer`
- [ ] `addCiscoVnmcResource`
- [ ] `replaceNetworkACLList`
- [x] `detachVolume`
- [x] `markDefaultZoneForAccount`
- [ ] `enableOutOfBandManagementForZone`
- [ ] `listLdapUsers`
- [ ] `changeServiceForSystemVm`
- [ ] `listIpForwardingRules`
- [ ] `deleteVMSnapshot`
- [ ] `listStoragePoolsMetrics`
- [ ] `rebootRouter`
- [x] `listStoragePools`
- [x] `findHostsForMigration`
- [ ] `updateHypervisorCapabilities`
- [ ] `enableCiscoNexusVSM`
- [ ] `dedicateGuestVlanRange`
- [ ] `listStaticRoutes`
- [ ] `listF5LoadBalancers`
- [ ] `listExternalLoadBalancers`
- [x] `updateIso`
- [ ] `listOpenDaylightControllers`
- [ ] `addBigSwitchBcfDevice`
- [ ] `deleteCounter`
- [ ] `issueOutOfBandManagementPowerAction`
- [ ] `deleteUser`
- [ ] `deleteNetworkDevice`
- [ ] `createPortForwardingRule`
- [ ] `dedicateZone`
- [x] `prepareTemplate` #125
- [ ] `assignToLoadBalancerRule`
- [ ] `tmProvisionVirtualMachine`
- [ ] `archiveAlerts`
- [ ] `deleteCiscoVnmcResource`
- [ ] `stopInternalLoadBalancerVM`
- [ ] `addBrocadeVcsDevice`
- [ ] `createDomain`
- [ ] `listExternalFirewalls`
- [ ] `login`
- [ ] `listHypervisorCapabilities`
- [ ] `addImageStore`
- [ ] `tmDestroyVirtualMachine`
- [ ] `getSolidFireAccountId`
- [ ] `listSupportedNetworkServices`
- [ ] `listRolePermissions`
- [ ] `listDedicatedGuestVlanRanges`
- [ ] `listNetworkACLs`
- [ ] `addNetworkServiceProvider`
- [ ] `deleteVpnGateway`
- [x] `copyTemplate` #125
- [ ] `createServiceOffering`
- [ ] `listNiciraNvpDeviceNetworks`
- [ ] `assignVirtualMachine`
- [ ] `deleteBigSwitchBcfDevice`
- [ ] `configureNetscalerLoadBalancer`
- [ ] `listOvsElements`
- [ ] `associateUcsProfileToBlade`
- [ ] `deleteNetworkServiceProvider`
- [ ] `deleteNetworkOffering`
- [ ] `dedicatePod`
- [ ] `listNetworkDevice`
- [ ] `updateStorageNetworkIpRange`
- [ ] `deleteOpenDaylightController`
- [x] `updateTemplate` #125
- [ ] `createVlanIpRange`
- [ ] `updateVpnConnection`
- [ ] `listPaloAltoFirewallNetworks`
- [ ] `getPathForVolume`
- [ ] `listUcsManagers`
- [ ] `changeServiceForRouter`
- [ ] `deleteLdapConfiguration`
- [x] `updateVolume`
- [ ] `listTrafficTypes`
- [ ] `addSecondaryStorage`
- [x] `updateAccount`
- [x] `disableAccount` #102
- [x] `listDomains`
- [ ] `listUsageTypes`
- [ ] `listNetworkACLLists`
- [x] `deleteTemplate` #125
- [ ] `deleteVPC`
- [ ] `updateVpnGateway`
- [ ] `releaseDedicatedGuestVlanRange`
- [x] `migrateVirtualMachine` #126 
- [x] `createTemplate` #125
- [ ] `listBaremetalRct`
- [ ] `listDedicatedClusters`
- [ ] `uploadCustomCertificate`
- [ ] `deleteVpnCustomerGateway`
- [ ] `enableOutOfBandManagementForCluster`
- [ ] `listPortForwardingRules`
- [ ] `updateTemplatePermissions`
- [ ] `listTrafficMonitors`
- [ ] `updatePortForwardingRule`
- [ ] `listBrocadeVcsDevices`
- [ ] `linkDomainToLdap`
- [ ] `deleteVpnConnection`
- [ ] `deleteF5LoadBalancer`
- [ ] `createNetworkACL`
- [ ] `listVpnCustomerGateways`
- [ ] `createGlobalLoadBalancerRule`
- [ ] `deleteNetscalerLoadBalancer`
- [ ] `listGlobalLoadBalancerRules`
- [ ] `deleteDiskOffering`
- [ ] `releaseDedicatedCluster`
- [ ] `createVirtualRouterElement`
- [ ] `createVPC`
- [ ] `deleteAutoScalePolicy`
- [ ] `deleteRole`
- [ ] `deleteCiscoNexusVSM`
- [ ] `listInternalLoadBalancerVMs`
- [ ] `listCiscoVnmcResources`
- [ ] `removeResourceDetail`
- [x] `listOsTypes`
- [ ] `removeGuestOs`
- [ ] `listSrxFirewallNetworks`
- [x] `detachIso`
- [ ] `deletePaloAltoFirewall`
- [ ] `deletePod`
- [ ] `listDeploymentPlanners`
- [x] `deleteCluster`
- [x] `prepareHostForMaintenance`
- [ ] `createRole`
- [ ] `removeRegion`
- [ ] `getVolumeiScsiName`
- [ ] `getUploadParamsForVolume`
- [ ] `updateAutoScaleVmProfile`
- [ ] `updateAutoScaleVmGroup`
- [ ] `enableAutoScaleVmGroup`
- [ ] `updateGuestOsMapping`
- [x] `listDiskOfferings`
- [ ] `updateHostPassword`
- [ ] `createPortableIpRange`
- [ ] `deleteCiscoAsa1000vResource`
- [x] `updateCluster`
- [ ] `listUcsProfiles`
- [ ] `listStorageProviders`
- [ ] `updateGlobalLoadBalancerRule`
- [ ] `createCondition`
- [ ] `listProjects`
- [x] `createAccount`
- [ ] `revertToVMSnapshot`
- [ ] `addGuestOs`
- [x] `listHostTags`
- [ ] `removeGuestOsMapping`
- [x] `registerIso`
- [ ] `listCiscoAsa1000vResources`
- [ ] `listElastistorVolume`
- [ ] `deletePortableIpRange`
- [ ] `listNiciraNvpDevices`
- [ ] `addBaremetalPxeKickStartServer`
- [ ] `listAlerts`
- [ ] `upgradeRouterTemplate`
- [x] `extractVolume`
- [ ] `listVlanIpRanges`
- [ ] `listNuageVspDevices`
- [x] `cancelHostMaintenance`
- [x] `updateZone`
- [ ] `listProjectAccounts`
- [ ] `addExternalLoadBalancer`
- [ ] `updateAutoScalePolicy`
- [ ] `createDiskOffering`
- [ ] `createLBHealthCheckPolicy`
- [ ] `lockUser`
- [ ] `listLBHealthCheckPolicies`
- [ ] `listDedicatedPods`
- [ ] `listVPCs`
- [x] `migrateVirtualMachineWithVolume`
- [ ] `addNetworkDevice`
- [x] `updateUser` #99
- [ ] `restartVPC`
- [ ] `removeCertFromLoadBalancer`
- [x] `addHost`
- [x] `attachVolume`
- [ ] `addBaremetalDhcp`
- [ ] `addTrafficMonitor`
- [ ] `listLoadBalancers`
- [ ] `updateProject`
- [ ] `deleteLBStickinessPolicy`
- [x] `listUsers` #99
- [ ] `listVpnConnections`
- [ ] `disableUser`
- [ ] `listIsos`
- [ ] `updateCloudToUseObjectStore`
- [ ] `listAutoScalePolicies`
- [ ] `addBaremetalRct`
- [ ] `updateRole`
- [ ] `listVmwareDcs`
- [ ] `listRemoteAccessVpns`
- [ ] `deleteNetworkACLList`
- [ ] `createServiceInstance`
- [ ] `releasePublicIpRange`
- [ ] `listNetscalerLoadBalancerNetworks`
- [x] `startSystemVm`
- [ ] `listNetworkIsolationMethods`
- [ ] `listStorageNetworkIpRange`
- [ ] `deleteDomain`
- [ ] `configureVirtualRouterElement`
- [ ] `migrateVolume`
- [ ] `configureSrxFirewall`
- [ ] `resetApiLimit`
- [ ] `createInternalLoadBalancerElement`
- [ ] `deleteVlanIpRange`
- [ ] `generateAlert`
- [ ] `addLdapConfiguration`
- [ ] `ldapConfig`
- [ ] `deletePortForwardingRule`
- [ ] `deleteGlobalLoadBalancerRule`
- [ ] `listBigSwitchBcfDevices`
- [x] `updateConfiguration`
- [ ] `dedicatePublicIpRange`
- [ ] `enableStaticNat`
- [ ] `deleteZone`
- [ ] `getUploadParamsForTemplate`
- [ ] `releaseDedicatedHost`
- [ ] `updateProjectInvitation`
- [x] `listRegions`
- [ ] `configureInternalLoadBalancerElement`
- [ ] `migrateSystemVm`
- [ ] `listCounters`
- [ ] `listVirtualRouterElements`
- [ ] `deleteSnapshotPolicies`
- [ ] `listTrafficTypeImplementors`
- [ ] `deleteImageStore`
- [ ] `listAutoScaleVmProfiles`
- [ ] `disableOutOfBandManagementForHost`
- [ ] `updateResourceCount`
- [ ] `listVpnGateways`
- [ ] `listRoles`
- [x] `getCloudIdentifier`
- [ ] `createLBStickinessPolicy`
- [ ] `configurePaloAltoFirewall`
- [ ] `addCiscoAsa1000vResource`
- [ ] `updateNetworkACLItem`
- [ ] `listRouters`
- [ ] `releaseHostReservation`
- [ ] `createVpnConnection`
- [ ] `listBrocadeVcsDeviceNetworks`
- [ ] `deletePhysicalNetwork`
- [ ] `dedicateHost`
- [ ] `removeVpnUser`
- [ ] `addGloboDnsHost`
- [ ] `logout`
- [ ] `deleteLBHealthCheckPolicy`
- [ ] `listSwifts`
- [ ] `enableOutOfBandManagementForHost`
- [ ] `deleteServiceOffering`
- [ ] `addNiciraNvpDevice`
- [ ] `addF5LoadBalancer`
- [ ] `listNetworkServiceProviders`
- [ ] `listInfrastructure`
- [ ] `listUsageRecords`
- [x] `deleteVolume`
- [ ] `enableUser`
- [ ] `listZonesMetrics`
- [x] `extractTemplate` #125 ?
- [ ] `suspendProject`
- [x] `getApiLimit` #128
- [ ] `deleteStorageNetworkIpRange`
- [ ] `addVmwareDc`
- [ ] `updateIsoPermissions`
- [x] `registerTemplate` #125
- [ ] `deleteVPCOffering`
- [ ] `addStratosphereSsp`
- [ ] `updateNuageVspDevice`
- [ ] `deleteNetworkACL`
- [ ] `createStoragePool`
- [x] `findStoragePoolsForMigration`
- [ ] `addOpenDaylightController`
- [ ] `createZone`
- [ ] `disableCiscoNexusVSM`
- [ ] `createStorageNetworkIpRange`
- [ ] `listDomainChildren`
- [ ] `assignToGlobalLoadBalancerRule`
- [ ] `configureOvsElement`
- [ ] `addImageStoreS3`
- [ ] `createPhysicalNetwork`
- [ ] `listAutoScaleVmGroups`
- [ ] `createFirewallRule`
- [x] `createVolume`
- [ ] `listF5LoadBalancerNetworks`
- [ ] `listVMSnapshot`
- [ ] `updatePod`
- [x] `attachIso`
- [ ] `listBaremetalDhcp`
- [ ] `tmMigrateVirtualMachine`
- [ ] `enableStorageMaintenance`
- [ ] `ldapRemove`
- [x] `createUser` #99
- [ ] `deleteBaremetalRct`
- [ ] `createVpnGateway`
- [ ] `addResourceDetail`
- [ ] `createVMSnapshot`
- [ ] `listVpnUsers`
- [ ] `deleteLoadBalancer`
- [ ] `deleteIpForwardingRule`
- [ ] `addRegion`
- [ ] `generateUsageRecords`
- [ ] `updateRolePermission`
- [ ] `cancelStorageMaintenance`
- [ ] `destroyRouter`
- [ ] `updateSnapshotPolicy`
- [ ] `listImageStores`
- [x] `deleteAccount`
- [ ] `createCounter`
- [ ] `disableOutOfBandManagementForCluster`
- [x] `addCluster`
- [ ] `deleteTrafficMonitor`
- [ ] `activateProject`
- [ ] `deleteSslCert`
- [x] `listDedicatedHosts`
- [ ] `deleteAutoScaleVmGroup`
- [ ] `listPaloAltoFirewalls`
- [ ] `updateLoadBalancerRule`
- [ ] `deleteAlerts`
- [x] `enableAccount` #102
- [ ] `createAutoScaleVmProfile`
- [ ] `listLBStickinessPolicies`
- [ ] `addUcsManager`
- [x] `reconnectHost`
- [ ] `deleteProject`
- [ ] `listNetscalerLoadBalancers`
- [ ] `addNetscalerLoadBalancer`
- [ ] `listIsoPermissions`
- [ ] `createLoadBalancer`
- [ ] `listBaremetalPxeServers`
- [ ] `addPaloAltoFirewall`
- [ ] `createPrivateGateway`
- [ ] `listLoadBalancerRules`
- [ ] `getUser`
- [ ] `deleteFirewallRule`
- [ ] `uploadSslCert`
- [ ] `createVpnCustomerGateway`
- [ ] `listCiscoNexusVSMs`
- [ ] `addVpnUser`
- [ ] `addBaremetalHost`
- [ ] `deleteRolePermission`
- [ ] `updateRemoteAccessVpn`
- [ ] `updateVPCOffering`
- [ ] `updateEgressFirewallRule`
- [x] `listOsCategories`
- [ ] `removeFromGlobalLoadBalancerRule`
- [x] `listCapacity`
- [ ] `updateServiceOffering`
- [ ] `createNetworkACLList`

**Comment by marcaurele** [comment]
Did my cherry-picking

**Comment by greut** [comment]
the hosts commands will be done at later times.
